backend:
  name: github
  repo: Blue084-end/Web1
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Tài liệu"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
